export enum USER_ACTION_TYPES {
    SET_CURRENT_USER = 'user/SET_CURRENT_USER',
    CHECK_USER_SESSION = 'user/CHECK_USER_SESSION',
    GOGLE_SIGN_IN_START = 'user/GOOGLE_SIGN_IN_START',
    EMAIL_SIGN_IN_START = 'user/EMAIL_SIGN_IN_START',
    SIGN_UP_STARTED = 'user/SIGN_UP_STARTED',
    SIGN_UP_SUCCEEDED = 'user/SIGN_UP_SUCCEEDED',
    SIGN_OUT_STARTED = 'user/SIGN_OUT_STARTED',
}