export const USER_ACTION_TYPES = {
    SET_CURRENT_USER: 'user/SET_CURRENT_USER',
    CHECK_USER_SESSION: 'user/CHECK_USER_SESSION',
    GOGLE_SIGN_IN_START: 'user/GOOGLE_SIGN_IN_START',
    EMAIL_SIGN_IN_START: 'user/EMAIL_SIGN_IN_START',
    SIGN_IN_SUCCESS: 'user/SIGN_IN_SUCCESS',
    SIGN_IN_FAILED: 'user/SIGN_IN_FAILED',
    SIGN_UP_STARTED: 'user/SIGN_UP_STARTED',
    SIGN_UP_SUCCEEDED: 'user/SIGN_UP_SUCCEEDED',
    SIGN_UP_FAILED: 'user/SIGN_UP_FAILED',
    SIGN_OUT_STARTED: 'user/SIGN_OUT_STARTED',
    SIGN_OUT_SUCCEEDED: 'user/SIGN_OUT_SUCCEEDED',
    SIGN_OUT_FAILED: 'user/SIGN_OUT_FAILED',
}